#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# aliases
alias zshconfig="$EDITOR ~/.zshrc"
alias vimconfig="$EDITOR ~/.vimrc"
alias tlf="tail -f"

alias sourcetree='open -a SourceTree'

alias rrg='rake routes | grep'
alias RET='RAILS_ENV=test'
alias bi='bundle install'
alias be='bundle exec'

function psgrep() { ps axu | grep -v grep | grep "$@" -i --color=auto; }
