#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# undo bad prezto config
unsetopt CORRECT
unalias rm

# aliases
alias zshconfig="$EDITOR ~/.zshrc"
alias vimconfig="$EDITOR ~/.vimrc"
alias tlf="tail -f"

alias st='open -a SourceTree'

alias rrg='bin/rake routes | grep'
alias RET='RAILS_ENV=test'
alias bi='bundle install'
alias be='bundle exec'
alias rs='bin/rails server'
alias rc='bin/rails console'
alias rdm='bundle exec rake db:migrate'
alias rsp='bin/rspec'

alias ta='tmux attach -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'

function psgrep() { ps axu | grep -v grep | grep "$@" -i --color=auto; }

# goto project
function goto() {
  cd ~/src/$1
}
export GOPATH=/Users/phil/src/go
